SELECT 
    *
FROM
    customer
LIMIT 5;

-- 1. What is the average purchase amount for each product category?

SELECT 
    category, avg(purchase_amount)
FROM
    customer
group by (category);

-- 2. How many customers made purchases in each season (Spring, Summer, Fall, Winter)?

SELECT 
    season, COUNT(customer_id) as no_of_customer_per_season
FROM
    customer
GROUP BY season;

-- 3. Which payment method is most commonly used by customers?

SELECT 
    payment_method, COUNT(customer_id) AS no_of_customer
FROM
    customer
GROUP BY payment_method
ORDER BY no_of_customer DESC
LIMIT 1;

-- 4. Find the top 5 locations with the highest total purchase amount.

SELECT 
    location, SUM(purchase_amount) as total_purchase_amount
FROM
    customer
GROUP BY location 
ORDER BY total_purchase_amount DESC
LIMIT 5;

-- 5. What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;

-- 6. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

-- 7. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

